// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otkxvzeujgwnrgfpcknh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a3h2emV1amd3bnJnZnBja25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDg4MTQsImV4cCI6MjA2NjYyNDgxNH0.vzjsd7Alss-dYd147_Sns25MOsrDggctPQIhCjBOORA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);